name: Build and Test copy_command on (Windows|MacOS|Ubuntu)x(x86)

on:
  push:
    paths:
      - 'copy_command/**'
      - '!copy_command/**/*.md'
  pull_request:
    paths:
      - 'copy_command/**'
      - '!copy_command/**/*.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      BUILD_TYPE: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: CMake Build (Windows)
      if: matrix.os == 'windows-latest'
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: copy_command
        build-dir: copy_command/build
        run-build: true
        build-args: --config ${{ env.BUILD_TYPE }}

    - name: CMake Build (Linux/Mac)
      if: matrix.os != 'windows-latest'
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: copy_command
        build-dir: copy_command/build
        run-build: true

    - name: CTest Test (Windows)
      if: matrix.os == 'windows-latest'
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: copy_command/build
        args: -C ${{ env.BUILD_TYPE }}
    - name: CTest Test (Windows)
      if: matrix.os != 'windows-latest'
      uses: threeal/ctest-action@v1.1.0
      with:
        test-dir: copy_command/build
  
  
